CREATE DATABASE IF NOT EXISTS flow;

DROP TABLE IF EXISTS flow.burst_v2;

CREATE TABLE flow.burst_v2
(
    `accel` Float64,
    `age_min` String,
    `block_time` String,
    `burst_age_slot` Int64,
    `cb_legacy` Float64,
    `cb_net` Float64,
    `cb_reset_gross` Float64,
    `censored_excl` Bool,
    `censored_incl` Bool,
    `curve_progress` Float64,
    `death_age_excl` Nullable(Int64),
    `death_age_incl` Nullable(Int64),
    `death_age_slot` Nullable(Int64),
    `depth_x` Float64,
    `event_seq` Int64,
    `fwd_net_flow_12slot` Float64,
    `fwd_net_flow_37slot` Float64,
    `fwd_net_flow_5slot` Float64,
    `fwd_price_ret_12slot` Float64,
    `hazard_censored` Bool,
    `held_from_buys` Float64,
    `held_from_transfers` Float64,
    `inner_ix_index` Int64,
    `launch_window_guard` Int64,
    `mayhem` Bool,
    `mayhem_at_launch` Bool,
    `minute_bucket` String,
    `n_buyers_12slot` Int64,
    `n_trades_25slot` Int64,
    `net_flow_12slot` Float64,
    `net_flow_25slot` Float64,
    `net_flow_3slot` Float64,
    `net_flow_5slot` Float64,
    `nf3_excl_pre_1` Float64,
    `nf3_excl_pre_2` Float64,
    `nf3_traj_75_incl_pre` Array(Float64),
    `nonzero_excl` Int64,
    `nonzero_incl` Int64,
    `oh_a` Float64,
    `oh_b` Float64,
    `oh_conc_a` Float64,
    `oh_conc_b` Float64,
    `oh_n_wallets_a` Int64,
    `oh_n_wallets_b` Int64,
    `oh_ratio_a` Float64,
    `oh_ratio_b` Float64,
    `outer_ix_index` Int64,
    `p_launch` Float64,
    `p_t` Float64,
    `qual_005` Bool,
    `qual_020` Bool,
    `quote_mint` Nullable(String),
    `round_frac_25slot` Float64,
    `size_cv_25slot` Float64,
    `slot` Int64,
    `token_created_at` String,
    `token_mint` String,
    `traj_len` Int64,
    `trigger_fee_sol` Float64,
    `trigger_is_buy` Bool,
    `trigger_sol` Float64,
    `trigger_tokens` Float64,
    `trigger_wallet` String,
    `tx_index` Int64,
    `v_latency_1slot` Float64,
    `v_latency_2slot` Float64,
    `v_latency_3slot` Float64,
    `v_latency_7slot` Float64,
    `v_latency_8slot` Float64,
    `x0_lam` Int64,
    `x_at_plus12` Float64,
    `x_at_plus37` Float64,
    `x_at_plus5` Float64,
    `x_end_slot` Float64,
    `y0_units` Int64,
    `y_at_plus12` Float64,
    `y_at_plus37` Float64,
    `y_at_plus5` Float64,
    `y_end_slot` Float64,
    `y_t` Float64,

    CONSTRAINT traj_len_75 CHECK length(`nf3_traj_75_incl_pre`) = 75
)
ENGINE = MergeTree
ORDER BY (`token_mint`, `slot`, `tx_index`, `outer_ix_index`, `inner_ix_index`);
